/* eslint-disable */
import { 
  Gamepad2, 
  BrainCircuit, 
  Keyboard, 
  Zap, 
  Hash, 
  Waypoints, 
  Grid3X3, 
  Grid2X2,
  Crosshair,
  SpellCheck,
  HelpCircle,
  Calculator,
  MonitorSmartphone,
  Bird,
  Box
} from "lucide-react";

export const GAMES = [
  {
    title: "Color Match",
    slug: "colormatch",
    description: "Does the meaning of the word match its color? Think fast before time runs out!",
    category: "Brain",
    image: "/images/colormatch.svg",
    color: "from-indigo-400 to-purple-500",
  },
  {
    title: "Pong",
    slug: "pong",
    description: "Classic neon paddle and ball arcade game against a smart AI.",
    category: "Arcade",
    image: "/images/pong.png",
    color: "from-cyan-400 to-blue-500",
  },
  {
    title: "Flappy Block",
    slug: "flappy",
    description: "Navigate a flying block through glass pipes. Don't crash!",
    category: "Arcade",
    image: "/images/flappy.png",
    color: "from-emerald-400 to-teal-500",
  },
  {
    title: "Wordle Clone",
    slug: "guessword",
    description: "Guess the hidden 5-letter word in 6 tries. A classic daily puzzle.",
    category: "Word",
    image: "/images/guessword.png",
    color: "from-green-400 to-emerald-500",
  },
  {
    title: "Tic-Tac-Toe",
    slug: "tictactoe",
    description: "Play against a smart AI. Can you beat the unbeatable algorithm?",
    category: "Logic",
    image: "/images/tictactoe.png",
    color: "from-pink-400 to-rose-500",
  },
  {
    title: "Brick Breaker",
    slug: "breaker",
    description: "Smash through colorful glass bricks with your paddle and ball.",
    category: "Arcade",
    image: "/images/breaker.png",
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Snake",
    slug: "snake",
    description: "The classic arcade game. Eat the food to grow, but don't crash into yourself!",
    category: "Arcade",
    image: "/images/snake.png",
    color: "from-green-400 to-emerald-600",
  },
  {
    title: "Memory Match",
    slug: "memory",
    description: "Test your memory. Flip the cards and find all the matching pairs in the fewest moves.",
    category: "Brain",
    image: "/images/memory.png",
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Typing Speed",
    slug: "typing",
    description: "How fast can you type? Test your WPM and accuracy with this typing challenge.",
    category: "Skills",
    image: "/images/typing.png",
    color: "from-purple-500 to-pink-600",
  },
  {
    title: "Reaction Time",
    slug: "reaction",
    description: "Measure your reflexes. Click as soon as the screen turns green!",
    category: "Reflexes",
    image: "/images/reaction.png",
    color: "from-yellow-400 to-amber-500",
  },
  {
    title: "Number Puzzle",
    slug: "puzzle",
    description: "Slide the tiles into the empty space to arrange them in order from 1 to 15.",
    category: "Brain",
    image: "/images/puzzle.png",
    color: "from-orange-400 to-rose-500",
  },
  {
    title: "Zip",
    slug: "zip",
    description: "Connect the numbers in sequential order with a single, continuous line without crossing.",
    category: "Puzzle",
    image: "/images/zip.png",
    color: "from-cyan-400 to-blue-500",
  },
  {
    title: "2048",
    slug: "2048",
    description: "Slide and merge matching tiles to reach the legendary 2048 tile.",
    category: "Puzzle",
    image: "/images/2048.png",
    color: "from-yellow-400 to-orange-500",
  },
  {
    title: "Sudoku",
    slug: "sudoku",
    description: "Fill the 9x9 grid so every row, column, and 3x3 box contains digits 1-9.",
    category: "Logic",
    image: "/images/sudoku.png",
    color: "from-indigo-400 to-purple-600",
  },
  {
    title: "Aim Trainer",
    slug: "aim",
    description: "Click the targets as fast as they appear to improve your mouse accuracy and speed.",
    category: "Reflexes",
    image: "/images/aim.png",
    color: "from-red-400 to-rose-600",
  },
  {
    title: "Word Scramble",
    slug: "scramble",
    description: "Unscramble the letters to find the hidden word before time runs out.",
    category: "Word",
    image: "/images/scramble.png",
    color: "from-emerald-400 to-teal-600",
  },
  {
    title: "Daily Quiz",
    slug: "quiz",
    description: "Test your general knowledge with a series of challenging trivia questions.",
    category: "Trivia",
    image: "/images/quiz.png",
    color: "from-pink-400 to-rose-500",
  },
  {
    title: "Math Challenge",
    slug: "math",
    description: "Solve arithmetic problems as quickly as possible. Addition, subtraction, and multiplication!",
    category: "Education",
    image: "/images/math.png",
    color: "from-blue-400 to-indigo-500",
  },
  {
    title: "Stickman Fight",
    slug: "stickman",
    description: "Battle endless waves of enemy stickmen in this fast-paced physics brawler.",
    category: "Action",
    image: "/images/stickman.png",
    color: "from-red-500 to-orange-600",
  }
];
